import { v4 as uuidv4 } from 'uuid'
import axios from 'axios'

export const state = () => ({
    pheDuyet: [
        {
            id: uuidv4(),
            tenNhanVien: 'Truong',
            maNhanVien: 'Truong',
            chucVu: 'Truong',
            phongBan: 'Truong',
            ngayDeTrinh: new Date().toISOString(),
            ngayCanHang: new Date().toISOString(),
            diaDiemLamViec: 'Truong',
            phuPhi: 'Truong',
            maChiPhi: 'Truong',
            soThamChieu: 'Truong',
            tongTienTamTinh: 1,
            trangThai: 'Approved',
            yeuCauMuaHangChiTiets: [
                {
                    id: uuidv4(),
                    ycmhId: uuidv4(),
                    tenHangHoa_DichVu: 'Truong',
                    xuatXu_Hang: 'Truong',
                    model_MaHieu: 'Truong',
                    soLuong: 1,
                    donVi: 'Truong',
                    soTienTamTinh: 1,
                    maHangMucTrienKhai: 'Truong',
                    ghiChu: 'Truong',
                },
            ],
        },
        {
            id: uuidv4(),
            tenNhanVien: 'Truong',
            maNhanVien: 'Truong',
            chucVu: 'Truong',
            phongBan: 'Truong',
            ngayDeTrinh: new Date().toISOString(),
            ngayCanHang: new Date().toISOString(),
            diaDiemLamViec: 'Truong',
            phuPhi: 'Truong',
            maChiPhi: 'Truong',
            soThamChieu: 'Truong',
            trangThai: 'Pending',
            tongTienTamTinh: 1,
            yeuCauMuaHangChiTiets: [
                {
                    id: uuidv4(),
                    ycmhId: uuidv4(),
                    tenHangHoa_DichVu: 'Truong',
                    xuatXu_Hang: 'Truong',
                    model_MaHieu: 'Truong',
                    soLuong: 1,
                    donVi: 'Truong',
                    soTienTamTinh: 1,
                    maHangMucTrienKhai: 'Truong',
                    ghiChu: 'Truong',
                },
            ],
        },
        {
            id: uuidv4(),
            tenNhanVien: 'Truong',
            maNhanVien: 'Truong',
            chucVu: 'Truong',
            phongBan: 'Truong',
            ngayDeTrinh: new Date().toISOString(),
            ngayCanHang: new Date().toISOString(),
            diaDiemLamViec: 'Truong',
            phuPhi: 'Truong',
            maChiPhi: 'Truong',
            trangThai: 'Not approved',
            soThamChieu: 'Truong',
            tongTienTamTinh: 1,
            yeuCauMuaHangChiTiets: [
                {
                    id: uuidv4(),
                    ycmhId: uuidv4(),
                    tenHangHoa_DichVu: 'Truong',
                    xuatXu_Hang: 'Truong',
                    model_MaHieu: 'Truong',
                    soLuong: 1,
                    donVi: 'Truong',
                    soTienTamTinh: 1,
                    maHangMucTrienKhai: 'Truong',
                    ghiChu: 'Truong',
                },
            ],
        },
        {
            id: uuidv4(),
            tenNhanVien: 'Truong',
            maNhanVien: 'Truong',
            chucVu: 'Truong',
            phongBan: 'Truong',
            ngayDeTrinh: new Date().toISOString(),
            ngayCanHang: new Date().toISOString(),
            diaDiemLamViec: 'Truong',
            phuPhi: 'Truong',
            maChiPhi: 'Truong',
            trangThai: 'Not approved',
            soThamChieu: 'Truong',
            tongTienTamTinh: 1,
            yeuCauMuaHangChiTiets: [
                {
                    id: uuidv4(),
                    ycmhId: uuidv4(),
                    tenHangHoa_DichVu: 'Truong',
                    xuatXu_Hang: 'Truong',
                    model_MaHieu: 'Truong',
                    soLuong: 1,
                    donVi: 'Truong',
                    soTienTamTinh: 1,
                    maHangMucTrienKhai: 'Truong',
                    ghiChu: 'Truong',
                },
            ],
        },
    ],
})
export const getters = {}
export const mutations = {}
export const actions = {}
